// Static site data generator: pre-renders everything the express server
// serves on the fly (setupRoutes.ts) into something a static host can serve:
//   --layout bundle (default):
//       gameData/bundle.index.json
//                       ONE small JSON index: format tag, version, entry
//                            count, the shard file names, and one manifest
//                            entry per resource. The client fetches only
//                            this up front and then HTTP-Range fetches each
//                            resource's bytes out of the shards on demand —
//                            instead of one huge whole-bundle download (or
//                            ~9000 individual requests, the GitHub Pages
//                            black-screen cause).
//       gameData/bundle.<i>.bin
//                       uncompressed payload shards (see SHARD_BYTES): the
//                            raw bytes of every resource, concatenated in
//                            manifest order; entries never straddle shards
//                            and each shard stays under the GitHub Pages
//                            ~100MiB per-file soft limit. Uncompressed
//                            because a gzip stream cannot be Range-seeked
//                            (and PNGs/MP3s are incompressible anyway).
//                            See nova/src/common/bundle_format.ts.
//       index.html          the site entry point with the deploy version
//                           injected (cache-busting query parameter on
//                           browser_bundle.js + window.NOVA_VERSION for the
//                           bundle loader).
//   --layout files:
//       gameData/data/{type}/{id}.{json|png|mp3}
//       gameData/ids.json
//       preloadData.json
//       settings/controls.json
//   (the plain directory tree, for the express dev server).
//
// Bundle and run it headless from the novajs root (the bundle must live
// inside the repo tree so that lamejs' lazy require() resolves):
//   npm run generate:static
// which is:
//   npx esbuild --bundle --platform=node --tsconfig=tsconfig.json \
//       scripts/generate_static.ts --outfile=scripts/generate_static_bundle.js
//   node scripts/generate_static_bundle.js [--layout bundle|files] \
//       [--out <dir>] [--data-path <dir>]
//
// The pipeline mirrors nova/server.ts: GameDataAggregator over FilesystemData
// (the git-tracked nova/objects overrides) and NovaParse (the real game
// data), minus the comlink/worker indirection.

import * as fs from "fs";
import * as path from "path";
import {
    BUNDLE_FORMAT,
    BUNDLE_VERSION,
    BundleEntry,
    BundleIndexHeader,
    SHARD_BYTES,
    validateHeader,
} from "nova/src/common/bundle_format";
import { FilesystemData, Paths, PathInfo } from "nova/src/server/parsing/FilesystemData";
import { GameDataAggregator } from "nova/src/server/parsing/GameDataAggregator";
import { NovaParse } from "novaparse/NovaParse";
import { currentVersion, injectVersion } from "./version";

// The bundle runs from scripts/, so these land inside the repo checkout.
const defaultDataPath = path.join(__dirname, "..", "nova", "Nova_Data");
const defaultObjectsPath = path.join(__dirname, "..", "nova", "objects");
const defaultOutDir = path.join(__dirname, "..", "dist-site");
const settingsPath = path.join(__dirname, "..", "nova", "settings");

function extensionForType(type: string): string {
    var pathInfo = (Paths as { [type: string]: PathInfo })[type];
    return pathInfo ? pathInfo.extension : "json";
}

// Serializes a resource the same way express' res.send() would transmit it:
// binary buffers byte-for-byte, everything else as JSON.
function serializeValue(value: unknown): Buffer | Uint8Array | string {
    if (value instanceof ArrayBuffer) {
        return Buffer.from(value);
    }
    if (Buffer.isBuffer(value) || value instanceof Uint8Array) {
        return value;
    }
    return JSON.stringify(value);
}

function listFilesRecursive(root: string): Array<string> {
    var results: Array<string> = [];
    for (var entry of fs.readdirSync(root, { withFileTypes: true })) {
        var fullPath = path.join(root, entry.name);
        if (entry.isDirectory()) {
            results = results.concat(listFilesRecursive(fullPath));
        }
        else {
            results.push(fullPath);
        }
    }
    return results;
}

// Where generated bytes go. Keys are the client-relative URLs the express
// route would serve (e.g. "gameData/data/Ship/nova:128.json"), so both
// layouts produce the same key space.
interface ResourceSink {
    add(url: string, data: Buffer | Uint8Array | string): void;
}

// --layout files: today's directory tree, one file per resource.
class FileSink implements ResourceSink {
    constructor(private outDir: string) { }

    add(url: string, data: Buffer | Uint8Array | string): void {
        var file = path.join(this.outDir, url);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, data);
    }
}

// --layout bundle: appends resource bytes into shards and records manifest
// entries, then writes gameData/bundle.index.json (see bundle_format.ts)
// plus one pure-payload gameData/bundle.<i>.bin per shard.
class BundleSink implements ResourceSink {
    // One chunk list per shard; chunks[0] starts empty (never rotated).
    private chunks: Array<Array<Buffer | Uint8Array>> = [[]];
    private entries: Array<BundleEntry> = [];
    private seen = new Set<string>();
    // Write cursor within the current shard.
    private offset = 0;

    add(url: string, data: Buffer | Uint8Array | string): void {
        if (this.seen.has(url)) {
            throw new Error("Duplicate bundle entry: " + url);
        }
        this.seen.add(url);
        var bytes = typeof data === "string" ? Buffer.from(data, "utf8") : data;
        // Shards must stay under the static host's per-file limit, and an
        // entry never straddles shards. Rotate only when the current shard
        // is non-empty: an entry bigger than SHARD_BYTES then lands in a
        // shard of its own, which the self-check fails below.
        if (this.offset > 0 && this.offset + bytes.byteLength > SHARD_BYTES) {
            this.chunks.push([]);
            this.offset = 0;
        }
        this.entries.push({
            url: url,
            shard: this.chunks.length - 1,
            offset: this.offset,
            length: bytes.byteLength,
        });
        this.chunks[this.chunks.length - 1].push(bytes);
        this.offset += bytes.byteLength;
    }

    get entryCount(): number {
        return this.entries.length;
    }

    // Writes the index + shard files and returns the index JSON.
    write(outDir: string): string {
        var gameDataDir = path.join(outDir, "gameData");
        fs.mkdirSync(gameDataDir, { recursive: true });
        // Client-relative names, fetchable straight from the page base.
        var shards = this.chunks.map((_, i) => "gameData/bundle." + i + ".bin");
        for (var i = 0; i < this.chunks.length; i += 1) {
            var fd = fs.openSync(path.join(gameDataDir, path.basename(shards[i])), "w");
            try {
                for (var chunk of this.chunks[i]) {
                    fs.writeSync(fd, chunk);
                }
            }
            finally {
                fs.closeSync(fd);
            }
        }

        var header: BundleIndexHeader = {
            format: BUNDLE_FORMAT,
            version: BUNDLE_VERSION,
            entryCount: this.entries.length,
            shards: shards,
            entries: this.entries,
        };
        validateHeader(header);
        var indexJson = JSON.stringify(header);
        fs.writeFileSync(path.join(gameDataDir, "bundle.index.json"), indexJson);
        return indexJson;
    }
}

function byteLengthOf(data: Buffer | Uint8Array | string): number {
    return typeof data === "string" ? Buffer.byteLength(data) : data.byteLength;
}

async function main() {
    var args = process.argv.slice(2);
    var layout: "bundle" | "files" = "bundle";
    var dataPath = defaultDataPath;
    var objectsPath = defaultObjectsPath;
    var outDir = defaultOutDir;
    for (var i = 0; i < args.length; i += 1) {
        if (args[i] === "--layout" && i + 1 < args.length) {
            var layoutArg = args[i + 1];
            if (layoutArg !== "bundle" && layoutArg !== "files") {
                console.error("Unknown --layout " + layoutArg
                    + " (expected 'bundle' or 'files')");
                return 1;
            }
            layout = layoutArg;
            i += 1;
        }
        else if (args[i] === "--data-path" && i + 1 < args.length) {
            dataPath = args[i + 1];
            i += 1;
        }
        else if (args[i] === "--out" && i + 1 < args.length) {
            outDir = args[i + 1];
            i += 1;
        }
    }
    outDir = path.resolve(outDir);

    console.log("Generating static data from " + path.resolve(dataPath)
        + " into " + outDir + " (layout " + layout + ") ...");

    // Start clean so stale files from earlier runs can't hide behind the
    // file-count self-check below.
    fs.rmSync(outDir, { recursive: true, force: true });

    // Same as nova/server.ts, minus the comlink/worker indirection.
    // Note: the plug-ins subdirectory must match the on-disk name under
    // dataPath (NovaParse's default, "Plug-ins"); the game data directory
    // itself is called "Nova Plug-ins" but is never referenced directly.
    var gameData = new GameDataAggregator([
        new FilesystemData(objectsPath),
        new NovaParse(dataPath, false, { novaFiles: "Nova Files", novaPlugins: "Plug-ins" }),
    ]);

    var ids = await gameData.ids;
    var sink: ResourceSink = layout === "files"
        ? new FileSink(outDir)
        : new BundleSink();
    var totalIDs = 0;
    var failures: Array<string> = [];

    for (var entry of Object.entries(ids)) {
        var type = entry[0];
        var typeIDs = entry[1];

        // Aggregator IDs are a concatenation across data sources; dedupe so
        // each file is written exactly once (the later write would win,
        // exactly like the express route).
        var uniqueIDs = Array.from(new Set(typeIDs));
        totalIDs += uniqueIDs.length;

        var extension = extensionForType(type);

        var gettable = (gameData.data as { [type: string]: { get(id: string): Promise<unknown> } })[type];
        if (!gettable) {
            failures.push("Unknown data type " + type);
            continue;
        }

        for (var id of uniqueIDs) {
            // .get() falls back to Defaults, same as the server's
            // requestFulfiller, so every ID produces a servable file.
            var value = await gettable.get(id);
            sink.add("gameData/data/" + type + "/" + id + "." + extension,
                serializeValue(value));
        }
        console.log("  " + type + ": " + uniqueIDs.length);
    }

    // Auxiliary files, served by setupRoutes from the aggregator directly.
    // In bundle layout the client reads these from the bundle, but plain
    // copies are kept on disk too so direct URLs (and smoke checks against
    // the deployed site) keep working.
    var aux: Array<[string, Buffer | Uint8Array | string]> = [
        ["gameData/ids.json", JSON.stringify(ids)],
        ["preloadData.json", JSON.stringify(await gameData.preloadData)],
        ["settings/controls.json",
            fs.readFileSync(path.join(settingsPath, "controls.json"))],
    ];
    for (var auxEntry of aux) {
        sink.add(auxEntry[0], auxEntry[1]);
        if (layout === "bundle") {
            var auxFile = path.join(outDir, auxEntry[0]);
            fs.mkdirSync(path.dirname(auxFile), { recursive: true });
            fs.writeFileSync(auxFile, auxEntry[1]);
        }
    }

    // The versioned entry point: build:site no longer copies the plain
    // template, so the generated index.html carries the deploy version
    // (cache-busting query parameter on browser_bundle.js +
    // window.NOVA_VERSION for the bundle loader). The loading overlay is
    // static content in the template.
    if (layout === "bundle") {
        var template = fs.readFileSync(
            path.join(__dirname, "..", "nova", "src", "index.html"), "utf8");
        fs.writeFileSync(path.join(outDir, "index.html"),
            injectVersion(template, currentVersion()));
    }

    // Self-verification: exactly one entry per ID plus the 3 auxiliary
    // files, and the bytes are servable — PNGs carry the PNG magic bytes,
    // MP3s carry a frame header (or are the empty default sound), JSON
    // files parse.
    if (layout === "files") {
        verifyFilesLayout(outDir, totalIDs, failures);
        if (failures.length === 0) {
            console.log("PASS: " + totalIDs + " resources + 3 auxiliary files");
        }
    }
    else {
        var bundleInfo = verifyBundleLayout(sink as BundleSink, outDir, totalIDs, failures);
        if (failures.length === 0) {
            var shardStats = bundleInfo.shardFiles.map(function(file) {
                return (fs.statSync(file).size / (1024 * 1024)).toFixed(1) + " MB "
                    + path.relative(outDir, file);
            });
            console.log("PASS: " + totalIDs + " resources + 3 auxiliary entries ("
                + (sink as BundleSink).entryCount + " entries in "
                + bundleInfo.shardFiles.length + " shards ["
                + shardStats.join(", ") + "], index "
                + (fs.statSync(bundleInfo.indexFile).size / 1024).toFixed(0) + " KB)");
        }
    }

    if (failures.length === 0) {
        return 0;
    }
    else {
        console.log("FAIL: " + failures.length + " of " + (totalIDs + 3)
            + " checks failed:");
        for (var failure of failures.slice(0, 20)) {
            console.log("  - " + failure);
        }
        return 1;
    }
}

function verifyContentBytes(url: string, bytes: Buffer, failures: Array<string>): void {
    if (url.endsWith(".png")) {
        if (bytes.length < 8 || bytes[0] !== 0x89 || bytes[1] !== 0x50
            || bytes[2] !== 0x4E || bytes[3] !== 0x47) {
            failures.push("Bad PNG magic: " + url);
        }
    }
    else if (url.endsWith(".mp3")) {
        // MPEG frame sync: 11 set bits. An empty entry is the default
        // sound (Defaults.SoundFile is an empty buffer) and is allowed.
        if (bytes.length > 0 && (bytes[0] !== 0xFF || (bytes[1] & 0xE0) !== 0xE0)) {
            failures.push("Bad MP3 frame header: " + url);
        }
    }
    else if (url.endsWith(".json")) {
        try {
            JSON.parse(bytes.toString("utf8"));
        }
        catch (e) {
            failures.push("Unparseable JSON: " + url);
        }
    }
}

function verifyFilesLayout(outDir: string, totalIDs: number, failures: Array<string>): void {
    var writtenFiles = listFilesRecursive(outDir);
    if (writtenFiles.length !== totalIDs + 3) {
        failures.push("Expected " + (totalIDs + 3) + " files, found " + writtenFiles.length);
    }

    for (var file of writtenFiles) {
        verifyContentBytes(path.relative(outDir, file), fs.readFileSync(file), failures);
    }
}

function verifyBundleLayout(bundleSink: BundleSink, outDir: string, totalIDs: number,
    failures: Array<string>): { indexFile: string, shardFiles: Array<string> } {
    var gameDataDir = path.join(outDir, "gameData");
    bundleSink.write(outDir);

    // Re-read the index from disk and validate it exactly like the client.
    var indexFile = path.join(gameDataDir, "bundle.index.json");
    var header = JSON.parse(fs.readFileSync(indexFile, "utf8")) as BundleIndexHeader;
    try {
        validateHeader(header);
    }
    catch (e) {
        failures.push("Invalid bundle index: " + e);
        return { indexFile: indexFile, shardFiles: [] };
    }

    if (header.entries.length !== totalIDs + 3
        || header.entryCount !== totalIDs + 3) {
        failures.push("Expected " + (totalIDs + 3) + " entries, found "
            + header.entries.length);
    }

    // Byte accounting per shard: the manifest is packed back to back from
    // offset 0 of each shard, and sum(length) === shard file size. Entries
    // were appended in order, so a shard change resets the cursor.
    var expectedOffset = 0;
    var currentShard = -1;
    var shardUsed = new Map<number, number>();
    for (var entry of header.entries) {
        if (entry.shard !== currentShard) {
            currentShard = entry.shard;
            expectedOffset = 0;
        }
        if (entry.offset !== expectedOffset) {
            failures.push("Non-contiguous manifest entry: " + entry.url);
        }
        expectedOffset = entry.offset + entry.length;
        shardUsed.set(currentShard, expectedOffset);
    }

    var shardFiles: Array<string> = [];
    for (var i = 0; i < header.shards.length; i += 1) {
        var shardFile = path.join(outDir, header.shards[i]);
        shardFiles.push(shardFile);
        var size = fs.statSync(shardFile).size;
        if ((shardUsed.get(i) ?? 0) !== size) {
            failures.push("Byte accounting mismatch for " + header.shards[i]
                + ": sum(entry.length) " + (shardUsed.get(i) ?? 0)
                + " !== file size " + size);
        }
        // GitHub Pages soft-limits files at ~100MiB; SHARD_BYTES leaves
        // headroom, so crossing 100MB means the rotation logic broke.
        if (size >= 100 * 1024 * 1024) {
            failures.push("Shard " + header.shards[i] + " is " + size
                + " bytes, at or above the 100MB static-host limit");
        }
    }

    // The bytes are servable: PNGs carry the PNG magic bytes, MP3s carry a
    // frame header (or are the empty default sound), JSON files parse.
    for (var i = 0; i < header.shards.length; i += 1) {
        var shard = fs.readFileSync(shardFiles[i]);
        for (var entry of header.entries) {
            if (entry.shard !== i) {
                continue;
            }
            verifyContentBytes(entry.url,
                shard.subarray(entry.offset, entry.offset + entry.length),
                failures);
        }
    }

    return { indexFile: indexFile, shardFiles: shardFiles };
}

main().then(function(code) {
    process.exit(code);
}, function(err) {
    console.error(err);
    process.exit(1);
});
