// Static site data generator: pre-renders everything the express server
// serves on the fly (setupRoutes.ts) into something a static host can serve:
//   --layout bundle (default):
//       gameData/bundle.bin.gz
//                       ONE gzip'd file: header + manifest + the raw bytes
//                            of every resource concatenated, so the client
//                            makes a single HTTP request instead of ~9000
//                            (the GitHub Pages black-screen cause). The
//                            client decompresses it with
//                            DecompressionStream('gzip') and falls back to
//                            an uncompressed gameData/bundle.bin when the
//                            .gz is missing or corrupt (older deployments).
//                            See nova/src/common/bundle_format.ts for the
//                            binary layout.
//       index.html          the site entry point with the deploy version
//                           injected (cache-busting query parameter on
//                           browser_bundle.js + window.NOVA_VERSION for the
//                           bundle loader).
//   --layout files:
//       gameData/data/{type}/{id}.{json|png|mp3}
//       gameData/ids.json
//       preloadData.json
//       settings/controls.json
//   (the plain directory tree, for the express dev server).
//
// Bundle and run it headless from the novajs root (the bundle must live
// inside the repo tree so that lamejs' lazy require() resolves):
//   npm run generate:static
// which is:
//   npx esbuild --bundle --platform=node --tsconfig=tsconfig.json \
//       scripts/generate_static.ts --outfile=scripts/generate_static_bundle.js
//   node scripts/generate_static_bundle.js [--layout bundle|files] \
//       [--out <dir>] [--data-path <dir>]
//
// The pipeline mirrors nova/server.ts: GameDataAggregator over FilesystemData
// (the git-tracked nova/objects overrides) and NovaParse (the real game
// data), minus the comlink/worker indirection.

import * as fs from "fs";
import * as path from "path";
import * as zlib from "zlib";
import {
    BUNDLE_FORMAT,
    BUNDLE_VERSION,
    BundleEntry,
    BundleHeader,
    decodeHeader,
    encodeHeader,
} from "nova/src/common/bundle_format";
import { FilesystemData, Paths, PathInfo } from "nova/src/server/parsing/FilesystemData";
import { GameDataAggregator } from "nova/src/server/parsing/GameDataAggregator";
import { NovaParse } from "novaparse/NovaParse";
import { currentVersion, injectVersion } from "./version";

// The bundle runs from scripts/, so these land inside the repo checkout.
const defaultDataPath = path.join(__dirname, "..", "nova", "Nova_Data");
const defaultObjectsPath = path.join(__dirname, "..", "nova", "objects");
const defaultOutDir = path.join(__dirname, "..", "dist-site");
const settingsPath = path.join(__dirname, "..", "nova", "settings");

function extensionForType(type: string): string {
    var pathInfo = (Paths as { [type: string]: PathInfo })[type];
    return pathInfo ? pathInfo.extension : "json";
}

// Serializes a resource the same way express' res.send() would transmit it:
// binary buffers byte-for-byte, everything else as JSON.
function serializeValue(value: unknown): Buffer | Uint8Array | string {
    if (value instanceof ArrayBuffer) {
        return Buffer.from(value);
    }
    if (Buffer.isBuffer(value) || value instanceof Uint8Array) {
        return value;
    }
    return JSON.stringify(value);
}

function listFilesRecursive(root: string): Array<string> {
    var results: Array<string> = [];
    for (var entry of fs.readdirSync(root, { withFileTypes: true })) {
        var fullPath = path.join(root, entry.name);
        if (entry.isDirectory()) {
            results = results.concat(listFilesRecursive(fullPath));
        }
        else {
            results.push(fullPath);
        }
    }
    return results;
}

// Where generated bytes go. Keys are the client-relative URLs the express
// route would serve (e.g. "gameData/data/Ship/nova:128.json"), so both
// layouts produce the same key space.
interface ResourceSink {
    add(url: string, data: Buffer | Uint8Array | string): void;
}

// --layout files: today's directory tree, one file per resource.
class FileSink implements ResourceSink {
    constructor(private outDir: string) { }

    add(url: string, data: Buffer | Uint8Array | string): void {
        var file = path.join(this.outDir, url);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, data);
    }
}

// --layout bundle: appends resource bytes and records manifest entries,
// then writes one bundle.bin = header (u32LE headerLength + header JSON,
// see bundle_format.ts) + payload.
class BundleSink implements ResourceSink {
    private chunks: Array<Buffer | Uint8Array> = [];
    private entries: Array<BundleEntry> = [];
    private seen = new Set<string>();
    private offset = 0;

    add(url: string, data: Buffer | Uint8Array | string): void {
        if (this.seen.has(url)) {
            throw new Error("Duplicate bundle entry: " + url);
        }
        this.seen.add(url);
        var bytes = typeof data === "string" ? Buffer.from(data, "utf8") : data;
        this.entries.push({ url: url, offset: this.offset, length: bytes.byteLength });
        this.chunks.push(bytes);
        this.offset += bytes.byteLength;
    }

    get entryCount(): number {
        return this.entries.length;
    }

    // Writes the bundle file and returns its total size in bytes.
    write(outFile: string): number {
        var header: BundleHeader = {
            format: BUNDLE_FORMAT,
            version: BUNDLE_VERSION,
            entryCount: this.entries.length,
            entries: this.entries,
        };
        var prefix = Buffer.from(encodeHeader(header));
        var fd = fs.openSync(outFile, "w");
        try {
            fs.writeSync(fd, prefix);
            for (var chunk of this.chunks) {
                fs.writeSync(fd, chunk);
            }
        }
        finally {
            fs.closeSync(fd);
        }
        return prefix.byteLength + this.offset;
    }
}

function byteLengthOf(data: Buffer | Uint8Array | string): number {
    return typeof data === "string" ? Buffer.byteLength(data) : data.byteLength;
}

async function main() {
    var args = process.argv.slice(2);
    var layout: "bundle" | "files" = "bundle";
    var dataPath = defaultDataPath;
    var objectsPath = defaultObjectsPath;
    var outDir = defaultOutDir;
    for (var i = 0; i < args.length; i += 1) {
        if (args[i] === "--layout" && i + 1 < args.length) {
            var layoutArg = args[i + 1];
            if (layoutArg !== "bundle" && layoutArg !== "files") {
                console.error("Unknown --layout " + layoutArg
                    + " (expected 'bundle' or 'files')");
                return 1;
            }
            layout = layoutArg;
            i += 1;
        }
        else if (args[i] === "--data-path" && i + 1 < args.length) {
            dataPath = args[i + 1];
            i += 1;
        }
        else if (args[i] === "--out" && i + 1 < args.length) {
            outDir = args[i + 1];
            i += 1;
        }
    }
    outDir = path.resolve(outDir);

    console.log("Generating static data from " + path.resolve(dataPath)
        + " into " + outDir + " (layout " + layout + ") ...");

    // Start clean so stale files from earlier runs can't hide behind the
    // file-count self-check below.
    fs.rmSync(outDir, { recursive: true, force: true });

    // Same as nova/server.ts, minus the comlink/worker indirection.
    // Note: the plug-ins subdirectory must match the on-disk name under
    // dataPath (NovaParse's default, "Plug-ins"); the game data directory
    // itself is called "Nova Plug-ins" but is never referenced directly.
    var gameData = new GameDataAggregator([
        new FilesystemData(objectsPath),
        new NovaParse(dataPath, false, { novaFiles: "Nova Files", novaPlugins: "Plug-ins" }),
    ]);

    var ids = await gameData.ids;
    var sink: ResourceSink = layout === "files"
        ? new FileSink(outDir)
        : new BundleSink();
    var totalIDs = 0;
    var failures: Array<string> = [];

    for (var entry of Object.entries(ids)) {
        var type = entry[0];
        var typeIDs = entry[1];

        // Aggregator IDs are a concatenation across data sources; dedupe so
        // each file is written exactly once (the later write would win,
        // exactly like the express route).
        var uniqueIDs = Array.from(new Set(typeIDs));
        totalIDs += uniqueIDs.length;

        var extension = extensionForType(type);

        var gettable = (gameData.data as { [type: string]: { get(id: string): Promise<unknown> } })[type];
        if (!gettable) {
            failures.push("Unknown data type " + type);
            continue;
        }

        for (var id of uniqueIDs) {
            // .get() falls back to Defaults, same as the server's
            // requestFulfiller, so every ID produces a servable file.
            var value = await gettable.get(id);
            sink.add("gameData/data/" + type + "/" + id + "." + extension,
                serializeValue(value));
        }
        console.log("  " + type + ": " + uniqueIDs.length);
    }

    // Auxiliary files, served by setupRoutes from the aggregator directly.
    // In bundle layout the client reads these from the bundle, but plain
    // copies are kept on disk too so direct URLs (and smoke checks against
    // the deployed site) keep working.
    var aux: Array<[string, Buffer | Uint8Array | string]> = [
        ["gameData/ids.json", JSON.stringify(ids)],
        ["preloadData.json", JSON.stringify(await gameData.preloadData)],
        ["settings/controls.json",
            fs.readFileSync(path.join(settingsPath, "controls.json"))],
    ];
    for (var auxEntry of aux) {
        sink.add(auxEntry[0], auxEntry[1]);
        if (layout === "bundle") {
            var auxFile = path.join(outDir, auxEntry[0]);
            fs.mkdirSync(path.dirname(auxFile), { recursive: true });
            fs.writeFileSync(auxFile, auxEntry[1]);
        }
    }

    // The versioned entry point: build:site no longer copies the plain
    // template, so the generated index.html carries the deploy version
    // (cache-busting query parameter on browser_bundle.js +
    // window.NOVA_VERSION for the bundle loader). The loading overlay is
    // static content in the template.
    if (layout === "bundle") {
        var template = fs.readFileSync(
            path.join(__dirname, "..", "nova", "src", "index.html"), "utf8");
        fs.writeFileSync(path.join(outDir, "index.html"),
            injectVersion(template, currentVersion()));
    }

    // Self-verification: exactly one entry per ID plus the 3 auxiliary
    // files, and the bytes are servable — PNGs carry the PNG magic bytes,
    // MP3s carry a frame header (or are the empty default sound), JSON
    // files parse.
    if (layout === "files") {
        verifyFilesLayout(outDir, totalIDs, failures);
        if (failures.length === 0) {
            console.log("PASS: " + totalIDs + " resources + 3 auxiliary files");
        }
    }
    else {
        var bundleInfo = verifyBundleLayout(sink as BundleSink, outDir, totalIDs, failures);
        if (failures.length === 0) {
            console.log("PASS: " + totalIDs + " resources + 3 auxiliary entries ("
                + (sink as BundleSink).entryCount + " entries, "
                + (fs.statSync(bundleInfo.gzFile).size / (1024 * 1024)).toFixed(1)
                + " MB " + path.relative(outDir, bundleInfo.gzFile)
                + ", uncompressed "
                + (bundleInfo.uncompressedBytes / (1024 * 1024)).toFixed(1) + " MB)");
        }
    }

    if (failures.length === 0) {
        return 0;
    }
    else {
        console.log("FAIL: " + failures.length + " of " + (totalIDs + 3)
            + " checks failed:");
        for (var failure of failures.slice(0, 20)) {
            console.log("  - " + failure);
        }
        return 1;
    }
}

function verifyContentBytes(url: string, bytes: Buffer, failures: Array<string>): void {
    if (url.endsWith(".png")) {
        if (bytes.length < 8 || bytes[0] !== 0x89 || bytes[1] !== 0x50
            || bytes[2] !== 0x4E || bytes[3] !== 0x47) {
            failures.push("Bad PNG magic: " + url);
        }
    }
    else if (url.endsWith(".mp3")) {
        // MPEG frame sync: 11 set bits. An empty entry is the default
        // sound (Defaults.SoundFile is an empty buffer) and is allowed.
        if (bytes.length > 0 && (bytes[0] !== 0xFF || (bytes[1] & 0xE0) !== 0xE0)) {
            failures.push("Bad MP3 frame header: " + url);
        }
    }
    else if (url.endsWith(".json")) {
        try {
            JSON.parse(bytes.toString("utf8"));
        }
        catch (e) {
            failures.push("Unparseable JSON: " + url);
        }
    }
}

function verifyFilesLayout(outDir: string, totalIDs: number, failures: Array<string>): void {
    var writtenFiles = listFilesRecursive(outDir);
    if (writtenFiles.length !== totalIDs + 3) {
        failures.push("Expected " + (totalIDs + 3) + " files, found " + writtenFiles.length);
    }

    for (var file of writtenFiles) {
        verifyContentBytes(path.relative(outDir, file), fs.readFileSync(file), failures);
    }
}

function verifyBundleLayout(bundleSink: BundleSink, outDir: string, totalIDs: number,
    failures: Array<string>): { gzFile: string, uncompressedBytes: number } {
    var bundleFile = path.join(outDir, "gameData", "bundle.bin");
    fs.mkdirSync(path.dirname(bundleFile), { recursive: true });
    var uncompressedBytes = bundleSink.write(bundleFile);
    var bundle = fs.readFileSync(bundleFile);

    var decoded = decodeHeader(bundle);
    if (decoded.header.entries.length !== totalIDs + 3
        || decoded.header.entryCount !== totalIDs + 3) {
        failures.push("Expected " + (totalIDs + 3) + " entries, found "
            + decoded.header.entries.length);
    }

    // Byte accounting: header prefix + payload === file size, and the
    // manifest is packed back to back starting at the payload start.
    var sum = 0;
    var expectedOffset = 0;
    for (var entry of decoded.header.entries) {
        if (entry.offset !== expectedOffset) {
            failures.push("Non-contiguous manifest entry: " + entry.url);
        }
        expectedOffset = entry.offset + entry.length;
        sum += entry.length;
    }
    if (decoded.payloadStart + sum !== uncompressedBytes) {
        failures.push("Byte accounting mismatch: payloadStart " + decoded.payloadStart
            + " + sum(entry.length) " + sum + " !== file size " + uncompressedBytes);
    }

    for (var entry of decoded.header.entries) {
        verifyContentBytes(entry.url,
            bundle.subarray(decoded.payloadStart + entry.offset,
                decoded.payloadStart + entry.offset + entry.length),
            failures);
    }

    // Deploy artifact: gzip the whole bundle into bundle.bin.gz. The site
    // ships only the .gz — the client decompresses it with
    // DecompressionStream('gzip') and falls back to an uncompressed
    // gameData/bundle.bin, which no deployment serves (dev uses the
    // --layout files tree). The plain file above exists only as the
    // self-check input.
    var gzFile = bundleFile + ".gz";
    fs.writeFileSync(gzFile, zlib.gzipSync(bundle));
    if (Buffer.compare(zlib.gunzipSync(fs.readFileSync(gzFile)), bundle) !== 0) {
        failures.push("Gzip round-trip mismatch: " + path.relative(outDir, gzFile));
    }
    fs.rmSync(bundleFile);
    return { gzFile: gzFile, uncompressedBytes: uncompressedBytes };
}

main().then(function(code) {
    process.exit(code);
}, function(err) {
    console.error(err);
    process.exit(1);
});
